name: Build Vyos Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag: 
        description: "The tag version you want to build"

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: sagitta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set version
      run: |
        if [[ -z "${{ github.event.inputs.tag }}" ]]; then
          echo "VYOS_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        else 
          echo "VYOS_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        fi

    - name: Pull vyos-build docker image
      run: |
        docker pull vyos/vyos-build:$BRANCH
        
    - name: Build iso
      run: |
        git clone -b $BRANCH --single-branch $GIT_CLONE_URL
        cd vyos-build
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:$BRANCH bash -c 'sudo ./build-vyos-image iso --architecture amd64 --build-type release --version "${{ env.VYOS_VERSION }}"'

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vyos-build/build/vyos-${{ env.VYOS_VERSION }}-amd64.iso
        tag: vyos-${{ env.BRANCH }}-${{ env.VYOS_VERSION }}
        overwrite: true
        file_glob: true
